### ISSUE TITLE
Privacy concern

### ISSUE THREAD

**Issue by vlec-be** [microsoft/cortana-samples#2]
Hi,

My girlfriend is working on a "paper" for her university to bring some answers regarding the Cortana API. How does it work when you use Cortana in your app ? Does the developer have access to the voice input data (eg : saving it into a file or sending back to a developer's server and then being able to read it in some way), and in the meantime does it also send the data back to Microsoft servers ? I hope that you will be able to give me a feedback for this, because I can't find anything in the official documentation. What kind of permission should the user accept and what consequences does it have ?
Thank you!

**Comment by rbrundritt** [comment]
Developers don't have access to the raw voice input. Instead they get access to a text version of what has been said. This is sent to the developers Cortana skill via a secure web service. Their skill then responds to service with an answer. The first time a user launches any skill created with the Cortana skills kit they are prompted to accept the terms of use of that skill and are also made aware of which user information the skill requests as well as a link to the privacy policy of the skill.
