### ISSUE TITLE
This is where the new cortana skills sdk samples link to and there is no code

### ISSUE THREAD

**Issue by v-tbert** [microsoft/cortana-samples#3]
Where is the sample code???

**Comment by rbrundritt** [comment]
I believe the links on the site you were on are all incorrect as it also points to the wrong forum currently. The team is trying to get these updated. I'm not sure who owns this GitHub project but will make a pull request to add links to the Cortana Skills samples. Note that Cortana skills currently can only be created using bot framework. As such nearly all the bot framework samples are relevant samples: https://github.com/Microsoft/BotBuilder-Samples 

There are also some samples on Cortana Skills which were part of the presentations at the Microsoft Build Conference: https://github.com/Microsoft/Cortana-Skills-Samples-Build-2017

**Comment by v-tbert** [comment]
Great, I will check those out. Thanks for the quick response….

**Comment by rbrundritt** [comment]
Looks like I have access to make changes on this repo. I've added links to samples and resources. Thanks for highlighting this issue.
